CREATE TABLE Customers(
    ID IDENTITY NOT NULL,
    SURNAME TEXT NOT NULL,
    DISTRICT TEXT NOT NULL,
    DISCOUNT DOUBLE NOT NULL,
    PRIMARY KEY (ID));

CREATE TABLE Books(
    ID IDENTITY NOT NULL,
    NAME TEXT NOT NULL,
    PRICE DOUBLE NOT NULL,
    STORAGE TEXT NOT NULL,
    COUNT INTEGER NOT NULL,
    PRIMARY KEY (ID));

CREATE TABLE Stores(
    ID IDENTITY NOT NULL,
    NAME TEXT NOT NULL,
    DISTRICT TEXT NOT NULL,
    COMMISSIONS DOUBLE NOT NULL,
    PRIMARY KEY (ID));

CREATE TABLE Purchases(
    NUMBER IDENTITY NOT NULL,
    PDATE DATE NOT NULL,
    STORE INTEGER NOT NULL,
    CUSTOMER INTEGER NOT NULL,
    BOOK INTEGER NOT NULL,
    COUNT INTEGER NOT NULL,
    PRICE DOUBLE NOT NULL,
    CONSTRAINT FK_STORE FOREIGN KEY (STORE)
        REFERENCES Stores (ID),
    CONSTRAINT FK_BOOK FOREIGN KEY (BOOK)
        REFERENCES Books (ID),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER)
        REFERENCES Customers (ID),
    PRIMARY KEY (NUMBER));
